- name: Descargar manifiesto de Calico
  get_url:
    url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
    dest: /tmp/calico.yaml

- name: Ajustar red de pods en el manifiesto de Calico
  replace:
    path: /tmp/calico.yaml
    regexp: '192.168.0.0/16'
    replace: '10.200.0.0/16'

- name: Aplicar Calico
  command: kubectl apply -f /tmp/calico.yaml
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"